### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HatsuMora** [pcingola/jFuzzyLogic#5]
Hi! 

I found your project useful but it's some times hard to use because doesn't have documentation, I think the manual it's great but often is a little hard to tell if exists a method that do something that the developers need. 

I think if implements an reference that explain briefly what each method does could be more helpful.

Thanks for jFuzzy!

**Comment by pcingola** [comment]
That's already done, have you checked the 'tipper.fcl" examples?

**Comment by pcingola** [comment]
That's already done, have you checked the 'tipper" examples?
Try running:
    java -jar jFuzzyLogic.jar demo

I hope this helps..
