### ISSUE TITLE
Create rules

### ISSUE THREAD

**Issue by mayuso** [pcingola/jFuzzyLogic#8]
Hello, I have been searching for a Fuzzy Logic related Java project and found this.
I have trouble with this API, I can´t really understand it well.

I have my data stored in about 10 excels (and growing each week), each of these has 4k rows and 55 columns.

What kind of data format does this API use? And more important, Can I use this API to create rules giving it some data?

Thank you in advance.

**Comment by pcingola** [comment]
Please read the documentations and take a look at the example programs.

**Comment by mayuso** [comment]
I already did, [Here](https://github.com/pcingola/jFuzzyLogic/wiki), that´s why I asked.

**Comment by pcingola** [comment]
http://jfuzzylogic.sourceforge.net/

**Comment by mayuso** [comment]
Ok, this is too hard for what I want to do xD I don´t really have time to learn "FCL" language. 

I guess I will find another API, thank you and good luck with your projects.
